services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: flask_expense_tracker_latest-combined # Build once and reuse
    restart: always
    env_file:
      - .env.local.docker
    depends_on:
      - db
      - redis
    ports:
      - "80:5000"
    command:
      [
        "/bin/sh",
        "-c",
        "flask db upgrade && flask run --host=0.0.0.0 --port=5000",
      ]
    volumes:
      - .:/app

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: expense_tracker_flask
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    restart: always
    env_file:
      - .env.local.docker
    ports:
      - "6379:6379"

  celery:
    image: flask_expense_tracker_latest-combined # Reuse the same image
    restart: always
    env_file:
      - .env.local.docker
    depends_on:
      - web
      - db
      - redis
    command: celery -A celery_worker.celery worker --loglevel=info

  celery_beat:
    image: flask_expense_tracker_latest-combined # Reuse the same image
    restart: always
    depends_on:
      - web
      - redis
    env_file:
      - .env.local.docker
    command: celery -A celery_worker.celery beat --loglevel=info

volumes:
  postgres_data:
