import enum

# For categories
CATEGORY_NAME_MIN_LENGTH = 1
CATEGORY_NAME_MAX_LENGTH = 100

# Add these constants to your existing constants file
WALLET_NAME_MIN_LENGTH = 1
WALLET_NAME_MAX_LENGTH = 100
DEFAULT_WALLET_NAME = "Bank"

AMOUNT_MIN_VALUE = 1
AMOUNT_MAX_VALUE = 99999999.99

# Pagination defaults
DEFAULT_PAGE_SIZE = 10
MAX_PAGE_SIZE = 100

# Budget constants
BUDGET_WARNING_THRESHOLD = 80
BUDGET_EXCEEDED_THRESHOLD = 100
