"""create recurring transaction model

Revision ID: 16de7ac2a182
Revises: 0a5987f40263
Create Date: 2025-03-17 13:25:37.484346

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = "16de7ac2a182"
down_revision = "0a5987f40263"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "recurring_transactions",
        sa.Column("amount", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "type",
            postgresql.ENUM(
                "CREDIT", "DEBIT", name="transaction_type", create_type=False
            ),
            nullable=False,
        ),
        sa.Column(
            "frequency",
            sa.Enum(
                "DAILY", "WEEKLY", "MONTHLY", "YEARLY", name="transaction_frequency"
            ),
            nullable=False,
        ),
        sa.Column("start_at", sa.DateTime(), nullable=False),
        sa.Column("end_at", sa.DateTime(), nullable=True),
        sa.Column("next_execution_at", sa.DateTime(), nullable=False),
        sa.Column("last_executed_at", sa.DateTime(), nullable=True),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("wallet_id", sa.UUID(), nullable=False),
        sa.Column("category_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["category_id"], ["categories.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["wallet_id"], ["wallets.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###
    # Instead of this


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("recurring_transactions")
    # ### end Alembic commands ###
