"""added index on foreign key

Revision ID: 235928fc3565
Revises: 25951c46696c
Create Date: 2025-03-27 00:41:05.157769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '235928fc3565'
down_revision = '25951c46696c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parent_child_relations', schema=None) as batch_op:
        batch_op.drop_constraint('parent_child_relations_parent_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('parent_child_relations_child_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['parent_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'users', ['child_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transactions_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_wallet_id'), ['wallet_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transactions_wallet_id'))
        batch_op.drop_index(batch_op.f('ix_transactions_user_id'))
        batch_op.drop_index(batch_op.f('ix_transactions_category_id'))

    with op.batch_alter_table('parent_child_relations', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('parent_child_relations_child_id_fkey', 'users', ['child_id'], ['id'])
        batch_op.create_foreign_key('parent_child_relations_parent_id_fkey', 'users', ['parent_id'], ['id'])

    # ### end Alembic commands ###
