"""Add notification tracking fields to budget model

Revision ID: 25951c46696c
Revises: 98a84a82ea99
Create Date: 2025-03-18 18:39:47.689557

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "25951c46696c"
down_revision = "98a84a82ea99"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("budgets", schema=None) as batch_op:
        batch_op.alter_column(
            "warning_notification_sent", existing_type=sa.BOOLEAN(), nullable=False
        )
        batch_op.alter_column(
            "exceeded_notification_sent", existing_type=sa.BOOLEAN(), nullable=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("budgets", schema=None) as batch_op:
        batch_op.alter_column(
            "exceeded_notification_sent", existing_type=sa.BOOLEAN(), nullable=True
        )
        batch_op.alter_column(
            "warning_notification_sent", existing_type=sa.BOOLEAN(), nullable=True
        )

    # ### end Alembic commands ###
