"""Add notification tracking fields to budget model

Revision ID: 98a84a82ea99
Revises: 16de7ac2a182
Create Date: 2025-03-18 18:36:57.996670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98a84a82ea99'
down_revision = '16de7ac2a182'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('budgets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('warning_notification_sent', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('exceeded_notification_sent', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('budgets', schema=None) as batch_op:
        batch_op.drop_column('exceeded_notification_sent')
        batch_op.drop_column('warning_notification_sent')

    # ### end Alembic commands ###
