"""create interwallet table

Revision ID: b52f4c702f62
Revises: 24538e78e4f7
Create Date: 2025-03-15 17:25:18.892341

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b52f4c702f62"
down_revision = "24538e78e4f7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "interwallet_transactions",
        sa.Column("amount", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("transaction_at", sa.DateTime(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("source_wallet_id", sa.UUID(), nullable=False),
        sa.Column("destination_wallet_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["destination_wallet_id"], ["wallets.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["source_wallet_id"], ["wallets.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("interwallet_transactions")
    # ### end Alembic commands ###
