"""remove index from trasaction

Revision ID: d60f2e3d05c9
Revises: 22ebaaafa87a
Create Date: 2025-03-27 13:01:47.608146

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd60f2e3d05c9'
down_revision = '22ebaaafa87a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index('ix_transactions_category_id')
        batch_op.drop_index('ix_transactions_user_id')
        batch_op.drop_index('ix_transactions_wallet_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.create_index('ix_transactions_wallet_id', ['wallet_id'], unique=False)
        batch_op.create_index('ix_transactions_user_id', ['user_id'], unique=False)
        batch_op.create_index('ix_transactions_category_id', ['category_id'], unique=False)

    # ### end Alembic commands ###
